import { SPORT_PHOTOS } from "./sportPhotos";
import { buildTemplatePages } from "./experienceTemplatePages";
import { TEMPLATE_NAV_TABS } from "./templatePageCopy";
import { TEMPLATE_ART } from "./templateArt";

import { DEFAULT_EXPERIENCE_PAGES } from "./experienceConfig";

import type {
  ExperienceBrand,
  ExperienceConfig,
  ExperienceEffects,
  ExperiencePageConfig,
  ExperienceTheme,
} from "./experienceConfig";

/**
 * Wix-style starter templates for the fan app. Each template is a themed
 * "look" (colors, buttons, fonts, effects) that can be applied on top of the
 * athlete's existing content without touching their copy or boxes.
 * Templates with a `landing` block are full layout templates — they also set
 * the landing page composition (copy, feature strip, CTA, social proof, stage).
 */
export type ExperienceTemplate = {
  id: string;
  label: string;
  vibe: string;
  /** Swatches shown in the gallery card, dark → accent. */
  swatches: string[];
  theme: Partial<ExperienceTheme>;
  effects: Partial<ExperienceEffects>;
  brand: Partial<ExperienceBrand>;
  /** Full-layout templates: landing page composition applied verbatim. */
  landing?: Partial<ExperiencePageConfig>;
  /** Filter chips in the gallery, e.g. ["dark","sport"]. */
  tags?: string[];
  /** Hero photo shown in the mini preview card. */
  photo?: string;
  /** Real athlete this reference template was designed for. */
  athlete?: string;
};

export const EXPERIENCE_TEMPLATES: ExperienceTemplate[] = [
  {
    id: "blank-canvas",
    label: "Blank Canvas",
    vibe: "Empty starting point — your photo, your colors, your copy",
    tags: ["blank", "minimal"],
    swatches: ["#08090B", "#12141A", "#FFFFFF", "#9AA3AF"],
    theme: {
      bg: "#08090B",
      bgGradientFrom: "#08090B",
      bgGradientVia: "#12141A",
      bgGradientTo: "#08090B",
      bgGradientAngle: 180,
      useGradientBg: true,
      accent: "#FFFFFF",
      accentHover: "#E5E7EB",
      buttonBg: "#FFFFFF",
      buttonText: "#08090B",
      buttonBorder: "transparent",
      buttonRadius: 999,
      text: "#FFFFFF",
      muted: "rgba(255,255,255,0.6)",
    },
    effects: {
      glow: false,
      particles: false,
      shimmer: false,
      vignette: false,
      noise: false,
      animatedGradient: false,
      glassmorphism: false,
    },
    brand: {
      logoColor: "#FFFFFF",
      logoTint: true,
      wordmarkColor: "#FFFFFF",
      tagline: "",
      taglineColor: "rgba(255,255,255,0.6)",
    },
    landing: {
      backgroundColor: "#08090B",
      backgroundGradientFrom: "rgba(255,255,255,0.04)",
      backgroundGradientTo: "#08090B",
      useGradientBg: true,
      accentColor: "#FFFFFF",
      effectPreset: "none",
      layoutMode: "freeform",
      heroImage: "",
      heroFit: "cover",
      heroPosition: "center",
      heroScale: 100,
      subhead: "",
      headline: "YOUR HEADLINE",
      headlineGradientFrom: "#FFFFFF",
      headlineGradientTo: "#FFFFFF",
      body: "Add your own photo, colors and copy — every layer here is editable.",
      ctaLabel: "ADD YOUR BUTTON",
      ctaBg: "#FFFFFF",
      ctaText: "#08090B",
      ctaGradientFrom: "#FFFFFF",
      ctaGradientTo: "#FFFFFF",
      ctaGradientAngle: 90,
      ctaRadius: 999,
      ctaShowArrow: true,
      showMenuButton: true,
      menuButtonColor: "rgba(255,255,255,0.8)",
      heroOverlayFrom: "rgba(8,9,11,0.05)",
      heroOverlayTo: "rgba(8,9,11,0.9)",
      heroOverlayOpacity: 100,
      features: [],
      stage: [
        { id: "hero", x: 0, y: 0, w: 100, h: 100, z: 4, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "logo", x: 5, y: 4, w: 12, z: 22, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "wordmark", x: 19, y: 4.5, w: 52, z: 21, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "tagline", x: 19, y: 8.5, w: 55, z: 20, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "titleArt", x: 10, y: 46, w: 70, z: 12, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "subhead", x: 6, y: 52, w: 88, z: 14, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "headline", x: 6, y: 58, w: 88, z: 15, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "body", x: 6, y: 68, w: 88, z: 13, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "featureRow", x: 5, y: 76, w: 90, z: 16, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "cardGrid", x: 4, y: 76, w: 92, z: 16, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "cta", x: 6, y: 86, w: 88, z: 18, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "memberProof", x: 5, y: 93, w: 90, z: 17, hidden: true, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
      ],
    },
  },
  {

    id: "join-the-circle",
    label: "Join The Circle",
    vibe: "Full cinematic layout — feature grid, gradient CTA, social proof",
    tags: ["dark", "sport", "bold"],
    photo: TEMPLATE_ART["join-the-circle"],
    swatches: ["#04070a", "#0a1b1f", "#25D8E8", "#8FF08A"],
    theme: {
      bg: "#04070a",
      bgGradientFrom: "#04070a",
      bgGradientVia: "#071417",
      bgGradientTo: "#020405",
      bgGradientAngle: 165,
      useGradientBg: true,
      accent: "#2FE0D6",
      accentHover: "#8FF08A",
      buttonBg: "#2FE0D6",
      buttonText: "#04140f",
      buttonBorder: "transparent",
      buttonRadius: 999,
      text: "#FFFFFF",
      muted: "rgba(255,255,255,0.62)",
    },
    effects: {
      glow: true,
      glowColor: "#2FE0D6",
      glowIntensity: 32,
      particles: false,
      shimmer: false,
      vignette: true,
      noise: true,
      noiseOpacity: 8,
      glassmorphism: true,
    },
    brand: {
      logoColor: "#2FE0D6",
      logoTint: true,
      wordmarkColor: "#FFFFFF",
      taglineColor: "rgba(255,255,255,0.7)",
      tagline: "One Circle. One Glow.",
    },
    landing: {
      backgroundColor: "#04070a",
      backgroundGradientFrom: "rgba(4,7,10,0.10)",
      backgroundGradientTo: "#04070a",
      useGradientBg: true,
      accentColor: "#2FE0D6",
      effectPreset: "glass",
      layoutMode: "freeform",
      heroImage: TEMPLATE_ART["join-the-circle"],
      heroFit: "cover",
      heroPosition: "center",
      heroScale: 100,
      subhead: "THE OFFICIAL\nFAN\nCOMMUNITY",
      headline: "Join The Circle",
      headlineGradientFrom: "#FFFFFF",
      headlineGradientTo: "#5CE9A6",
      body: "Exclusive drops, early access, giveaways, content, and real connection with your fans.",
      ctaLabel: "JOIN THE CIRCLE",
      ctaText: "#04140f",
      ctaGradientFrom: "#25D8E8",
      ctaGradientTo: "#A6F276",
      ctaGradientAngle: 90,
      ctaRadius: 999,
      ctaShowArrow: true,
      showMenuButton: true,
      menuButtonColor: "rgba(47,224,214,0.9)",
      heroOverlayFrom: "rgba(4,7,10,0.05)",
      heroOverlayTo: "rgba(4,7,10,0.92)",
      heroOverlayOpacity: 100,
      featureBg: "rgba(255,255,255,0.045)",
      featureBorderColor: "rgba(47,224,214,0.24)",
      featureIconColor: "#2FE0D6",
      featureTextColor: "#FFFFFF",
      featureRadius: 18,
      featureColumns: 4,
      features: [
        { id: "f1", icon: "star", label: "EXCLUSIVE DROPS" },
        { id: "f2", icon: "clock", label: "EARLY ACCESS" },
        { id: "f3", icon: "gift", label: "SPECIAL GIVEAWAYS" },
        { id: "f4", icon: "users", label: "REAL CONNECTION" },
      ],
      memberProof: {
        count: "25K+",
        label: "Members",
        extraLabel: "+12",
        avatars: [],
        thumbs: [],
        bg: "rgba(255,255,255,0.045)",
        borderColor: "rgba(255,255,255,0.12)",
        countColor: "#2FE0D6",
        labelColor: "rgba(255,255,255,0.62)",
        radius: 20,
      },
      stage: [
        { id: "hero", x: 0, y: 0, w: 100, h: 100, z: 4, glow: false, glowColor: "#2FE0D6", glowIntensity: 0 },
        { id: "logo", x: 14, y: 6.5, w: 12, z: 22, glow: true, glowColor: "#2FE0D6", glowIntensity: 45 },
        { id: "wordmark", x: 27, y: 7.5, w: 60, z: 21, scale: 118, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "tagline", x: 27, y: 11, w: 60, z: 20, scale: 112, glow: false, glowColor: "#2FE0D6", glowIntensity: 0 },
        { id: "titleArt", x: 10, y: 46, w: 70, z: 12, hidden: true, glow: false, glowColor: "#2FE0D6", glowIntensity: 0 },
        { id: "subhead", x: 8, y: 48, w: 84, z: 14, glow: false, glowColor: "#2FE0D6", glowIntensity: 22 },
        { id: "headline", x: 5, y: 54.5, w: 90, z: 15, scale: 150, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "body", x: 9, y: 62.5, w: 82, z: 13, scale: 106, glow: false, glowColor: "#FFFFFF", glowIntensity: 0 },
        { id: "featureRow", x: 5, y: 70, w: 90, z: 16, glow: false, glowColor: "#2FE0D6", glowIntensity: 0 },
        { id: "cta", x: 6, y: 80, w: 88, z: 18, glow: true, glowColor: "#5CE9A6", glowIntensity: 40 },
        { id: "memberProof", x: 5, y: 88.5, w: 90, z: 17, glow: false, glowColor: "#2FE0D6", glowIntensity: 0 },
      ],
    },
  },

  {
    id: "mint-night",
    label: "Mint Night",
    vibe: "Dark, clean, tennis-court calm",
    swatches: ["#050505", "#0A1A12", "#7CE7B0", "#A8F0CC"],
    theme: {
      bg: "#050505",
      bgGradientFrom: "#050505",
      bgGradientVia: "#0A1A12",
      bgGradientTo: "#05140E",
      bgGradientAngle: 160,
      useGradientBg: true,
      accent: "#7CE7B0",
      accentHover: "#A8F0CC",
      buttonBg: "#7CE7B0",
      buttonText: "#04231A",
      buttonBorder: "#7CE7B0",
      buttonRadius: 999,
      text: "#FFFFFF",
      muted: "#A3B3AA",
    },
    effects: { glow: true, glowColor: "#7CE7B0", glowIntensity: 45, particles: false, vignette: true },
    brand: { wordmarkColor: "#7CE7B0", taglineColor: "#A8F0CC" },
  },
  {
    id: "court-crimson",
    label: "Court Crimson",
    vibe: "Bold game-day energy",
    swatches: ["#080404", "#240A0C", "#ED2B3A", "#FF7A85"],
    theme: {
      bg: "#080404",
      bgGradientFrom: "#080404",
      bgGradientVia: "#240A0C",
      bgGradientTo: "#120506",
      bgGradientAngle: 155,
      useGradientBg: true,
      accent: "#ED2B3A",
      accentHover: "#FF7A85",
      buttonBg: "#ED2B3A",
      buttonText: "#FFFFFF",
      buttonBorder: "#ED2B3A",
      buttonRadius: 14,
      text: "#FFFFFF",
      muted: "#C6A9AC",
    },
    effects: { glow: true, glowColor: "#ED2B3A", glowIntensity: 55, particles: false, vignette: true },
    brand: { wordmarkColor: "#FFFFFF", taglineColor: "#FF7A85" },
  },
  {
    id: "gold-standard",
    label: "Gold Standard",
    vibe: "Luxury, championship, editorial",
    swatches: ["#0A0803", "#1C1608", "#D4AF37", "#F3DC96"],
    theme: {
      bg: "#0A0803",
      bgGradientFrom: "#0A0803",
      bgGradientVia: "#1C1608",
      bgGradientTo: "#0A0803",
      bgGradientAngle: 170,
      useGradientBg: true,
      accent: "#D4AF37",
      accentHover: "#F3DC96",
      buttonBg: "#D4AF37",
      buttonText: "#1A1204",
      buttonBorder: "#D4AF37",
      buttonRadius: 4,
      text: "#FFF8E7",
      muted: "#B9AC8B",
    },
    effects: { glow: true, glowColor: "#D4AF37", glowIntensity: 35, shimmer: true, vignette: true },
    brand: { wordmarkColor: "#D4AF37", taglineColor: "#F3DC96" },
  },
  {
    id: "electric-pop",
    label: "Electric Pop",
    vibe: "Hot pink, loud, gen-z",
    swatches: ["#07040A", "#1B0722", "#FF2D95", "#8B5CF6"],
    theme: {
      bg: "#07040A",
      bgGradientFrom: "#07040A",
      bgGradientVia: "#1B0722",
      bgGradientTo: "#0B0416",
      bgGradientAngle: 145,
      useGradientBg: true,
      accent: "#FF2D95",
      accentHover: "#FF6FB8",
      buttonBg: "#FF2D95",
      buttonText: "#FFFFFF",
      buttonBorder: "#FF2D95",
      buttonRadius: 999,
      text: "#FFFFFF",
      muted: "#C3A8D2",
    },
    effects: {
      glow: true,
      glowColor: "#FF2D95",
      glowIntensity: 65,
      particles: true,
      particleColor: "#8B5CF6",
      animatedGradient: true,
    },
    brand: { wordmarkColor: "#FF2D95", taglineColor: "#FFFFFF" },
  },
  {
    id: "ice-blue",
    label: "Ice Blue",
    vibe: "Cool, technical, performance",
    swatches: ["#03060B", "#08182A", "#38BDF8", "#BAE6FD"],
    theme: {
      bg: "#03060B",
      bgGradientFrom: "#03060B",
      bgGradientVia: "#08182A",
      bgGradientTo: "#040A14",
      bgGradientAngle: 165,
      useGradientBg: true,
      accent: "#38BDF8",
      accentHover: "#BAE6FD",
      buttonBg: "#38BDF8",
      buttonText: "#04121D",
      buttonBorder: "#38BDF8",
      buttonRadius: 12,
      text: "#F2FAFF",
      muted: "#9CB3C4",
    },
    effects: { glow: true, glowColor: "#38BDF8", glowIntensity: 40, blurBackdrop: true, glassmorphism: true },
    brand: { wordmarkColor: "#FFFFFF", taglineColor: "#BAE6FD" },
  },
  {
    id: "chalk-white",
    label: "Chalk",
    vibe: "Minimal light mode, print-clean",
    swatches: ["#F7F7F5", "#E8E8E4", "#111111", "#5B5B57"],
    theme: {
      bg: "#F7F7F5",
      bgGradientFrom: "#FFFFFF",
      bgGradientVia: "#F1F1EE",
      bgGradientTo: "#E8E8E4",
      bgGradientAngle: 180,
      useGradientBg: true,
      accent: "#111111",
      accentHover: "#333333",
      buttonBg: "#111111",
      buttonText: "#FFFFFF",
      buttonBorder: "#111111",
      buttonRadius: 8,
      text: "#111111",
      muted: "#5B5B57",
    },
    effects: {
      glow: false,
      particles: false,
      noise: false,
      shimmer: false,
      vignette: false,
      animatedGradient: false,
      glassmorphism: false,
    },
    brand: { wordmarkColor: "#111111", taglineColor: "#5B5B57" },
  },
];

/* ------------------------------------------------------------------ *
 * Sport-specific full-layout templates (Choose a template gallery).
 * Every one ships the complete landing composition: wordmark + tagline,
 * hero photo slot, big headline, body, 4-icon feature strip, arrow CTA
 * and the members social-proof row — exactly like the reference sheet.
 * ------------------------------------------------------------------ */

type FullTemplateSpec = {
  id: string;
  label: string;
  vibe: string;
  wordmark: string;
  tagline: string;
  headline: string;
  body: string;
  cta: string;
  features: [string, string, string, string];
  icons?: [string, string, string, string];
  count: string;
  countLabel: string;
  extra: string;
  /** dark page bg */
  bg: string;
  bgVia: string;
  accent: string;
  accentHover: string;
  ctaBg: string;
  ctaTo?: string;
  ctaText: string;
  text: string;
  muted: string;
  radius?: number;
  light?: boolean;
  /** key in SPORT_PHOTOS */
  photo: string;
  /** script signature line rendered as its own layer */
  signature?: string;
  /** editable pill in the top nav */
  badge?: string;
  /** 2x2 card grid — title / subtitle / icon / destination page */
  cards?: [string, string][];
  tags: string[];
  /** Real athlete this reference template was designed for. */
  athlete?: string;
};

function fullTemplate(s: FullTemplateSpec): ExperienceTemplate {
  const radius = s.radius ?? 10;
  const icons = s.icons ?? ["bolt", "video", "lock", "users"];
  const featureText = s.light ? "#111111" : "#FFFFFF";
  const line = s.light ? "rgba(0,0,0,0.12)" : "rgba(255,255,255,0.12)";
  const panel = s.light ? "rgba(0,0,0,0.04)" : "rgba(255,255,255,0.045)";
  return {
    id: s.id,
    label: s.label,
    vibe: s.vibe,
    tags: s.tags,
    athlete: s.athlete,
    photo: TEMPLATE_ART[s.id] ?? SPORT_PHOTOS[s.photo] ?? SPORT_PHOTOS.other,
    swatches: [s.bg, s.bgVia, s.accent, s.ctaTo ?? s.accentHover],
    theme: {
      bg: s.bg,
      bgGradientFrom: s.bg,
      bgGradientVia: s.bgVia,
      bgGradientTo: s.bg,
      bgGradientAngle: 165,
      useGradientBg: true,
      accent: s.accent,
      accentHover: s.accentHover,
      buttonBg: s.ctaBg,
      buttonText: s.ctaText,
      buttonBorder: "transparent",
      buttonRadius: radius,
      text: s.text,
      muted: s.muted,
    },
    effects: {
      glow: !s.light,
      glowColor: s.accent,
      glowIntensity: s.light ? 0 : 26,
      particles: false,
      shimmer: false,
      vignette: !s.light,
      noise: !s.light,
      noiseOpacity: 6,
      glassmorphism: true,
      animatedGradient: false,
    },
    brand: {
      logoColor: s.accent,
      logoTint: true,
      wordmarkColor: s.text,
      tagline: s.tagline,
      taglineColor: s.muted,
    },
    landing: {
      backgroundColor: s.bg,
      backgroundGradientFrom: s.light ? "rgba(255,255,255,0.10)" : "rgba(0,0,0,0.10)",
      backgroundGradientTo: s.bg,
      useGradientBg: true,
      accentColor: s.accent,
      effectPreset: s.light ? "soft" : "glass",
      layoutMode: "freeform",
      heroImage: TEMPLATE_ART[s.id] ?? SPORT_PHOTOS[s.photo] ?? SPORT_PHOTOS.other,
      heroFit: "cover",
      heroPosition: "center",
      heroScale: 100,
      subhead: "",
      headline: s.headline,
      headlineGradientFrom: s.text,
      headlineGradientTo: s.text,
      body: s.body,
      ctaLabel: s.cta,
      ctaBg: s.ctaBg,
      ctaText: s.ctaText,
      ctaGradientFrom: s.ctaBg,
      ctaGradientTo: s.ctaTo ?? s.ctaBg,
      ctaGradientAngle: 90,
      ctaRadius: radius,
      ctaShowArrow: true,
      showMenuButton: true,
      menuButtonColor: s.light ? "rgba(0,0,0,0.65)" : "rgba(255,255,255,0.8)",
      featureBg: "transparent",
      featureBorderColor: "transparent",
      featureIconColor: s.accent,
      featureTextColor: featureText,
      featureRadius: 12,
      featureColumns: 4,
      features: s.features.map((label, i) => ({
        id: `f${i + 1}`,
        icon: icons[i],
        label,
      })),

      heroOverlayFrom: s.light ? "rgba(255,255,255,0.05)" : "rgba(0,0,0,0.18)",
      heroOverlayTo: s.light ? "rgba(255,255,255,0.75)" : "rgba(0,0,0,0.88)",
      heroOverlayOpacity: 100,
      navLabel: s.wordmark,
      navTextColor: s.text,
      navBadgeLabel: s.badge ?? "Inner Circle",
      navBadgeColor: s.accent,
      navBadgeBorderColor: line,
      navBadgeRadius: 999,
      showNavBadge: true,
      showNavBell: true,
      showNavAvatar: true,
      navAvatarSrc: "",
      signatureText: s.signature ?? "",
      signatureImage: "",
      signatureColor: s.accent,
      signatureFont: "default",
      cardBg: panel,
      cardBorderColor: line,
      cardRadius: 18,
      cardTitleColor: featureText,
      cardTextColor: s.muted,
      cardIconColor: s.accent,
      cardColumns: 2,
      cards: (s.cards ?? s.features.map((label) => [label, ""] as [string, string])).map(
        ([title, subtitle], i) => ({
          id: `c${i + 1}`,
          title,
          subtitle,
          icon: icons[i] ?? "star",
          image: "",
          linkPageKey: ["community", "videos", "news", "shop"][i] ?? "home",
        }),
      ),
      memberProof: {
        count: s.count,
        label: s.countLabel,
        extraLabel: s.extra,
        avatars: [],
        thumbs: [],
        bg: panel,
        borderColor: line,
        countColor: s.accent,
        labelColor: s.muted,
        radius: 14,
      },
      stage: [
        { id: "logo", x: 5, y: 2.5, w: 11, z: 22, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "wordmark", x: 18, y: 3, w: 54, z: 21, align: "left", glow: false, glowColor: s.text, glowIntensity: 0 },
        { id: "tagline", x: 18, y: 6.5, w: 55, z: 20, align: "left", hidden: true, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "hero", x: 0, y: 0, w: 100, h: 100, z: 5, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "titleArt", x: 10, y: 46, w: 70, z: 12, hidden: true, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "subhead", x: 6, y: 48, w: 88, z: 14, align: "left", hidden: true, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "headline", x: 6, y: 52, w: 84, z: 15, scale: 104, align: "left", glow: false, glowColor: s.text, glowIntensity: 0 },
        { id: "body", x: 6, y: 63.5, w: 82, z: 13, align: "left", glow: false, glowColor: s.text, glowIntensity: 0 },
        { id: "navBar", x: 4, y: 11, w: 92, z: 24, hidden: true, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "signature", x: 6, y: 62, w: 44, z: 19, hidden: !s.signature, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "cardGrid", x: 4, y: 70, w: 92, z: 16, hidden: true, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "featureRow", x: 4, y: 73, w: 92, z: 16, glow: false, glowColor: s.accent, glowIntensity: 0 },
        { id: "cta", x: 5, y: 84, w: 90, z: 18, glow: !s.light, glowColor: s.accent, glowIntensity: 30 },
        { id: "memberProof", x: 5, y: 91.5, w: 90, z: 17, glow: false, glowColor: s.accent, glowIntensity: 0 },
      ],

    },
  };
}

const SPORT_TEMPLATE_SPECS: FullTemplateSpec[] = [
  {
    id: "gridiron",
    photo: "football",
    tags: ["dark", "sport", "bold"],
    label: "Gridiron",
    vibe: "Football — lime energy, night-practice grit",
    wordmark: "GRIDIRON",
    tagline: "Train. Compete. Dominate.",
    headline: "JOIN THE ELITE",
    body: "Exclusive drills, pro insights, and a community built for athletes who never settle.",
    cta: "JOIN THE TEAM",
    features: ["TRAINING PROGRAMS", "GAME ANALYSIS", "EXCLUSIVE CONTENT", "ATHLETE COMMUNITY"],
    icons: ["trophy", "video", "lock", "users"],
    count: "25K+",
    countLabel: "Athletes",
    extra: "+12",
    bg: "#050705",
    bgVia: "#0d1a0a",
    accent: "#B6F23C",
    accentHover: "#D2FA7A",
    ctaBg: "#B6F23C",
    ctaText: "#0d1a05",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.62)",
  },
  {
    id: "deep-end",
    photo: "swimming",
    tags: ["dark", "sport", "vibrant"],
    label: "Deep End",
    vibe: "Swimming — deep blue water light",
    wordmark: "DEEP END",
    tagline: "Go deeper. Get stronger.",
    headline: "BUILT IN\nTHE DEEP",
    body: "Swim programs, technique tips, and a community that pushes you further.",
    cta: "DIVE IN",
    features: ["WORKOUTS", "TECHNIQUE", "NUTRITION", "COMMUNITY"],
    icons: ["bolt", "sparkle", "heart", "users"],
    count: "12K+",
    countLabel: "Swimmers",
    extra: "+8",
    bg: "#03101c",
    bgVia: "#08283f",
    accent: "#1E9EE8",
    accentHover: "#7DD3FC",
    ctaBg: "#1E9EE8",
    ctaText: "#04121d",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.65)",
  },
  {
    id: "overtime",
    photo: "basketball",
    tags: ["dark", "sport", "bold"],
    label: "Overtime",
    vibe: "Basketball — arena orange under the lights",
    wordmark: "OVERTIME",
    tagline: "Every possession matters.",
    headline: "HOOPS. CULTURE.\nRELENTLESS.",
    body: "Skill workouts, film sessions, and a brotherhood built different.",
    cta: "JOIN OVERTIME",
    features: ["SKILL TRAINING", "FILM ROOM", "EVENTS", "COMMUNITY"],
    icons: ["bolt", "video", "calendar", "users"],
    count: "18K+",
    countLabel: "Hoopers",
    extra: "+10",
    bg: "#070403",
    bgVia: "#1f0d04",
    accent: "#F97316",
    accentHover: "#FDBA74",
    ctaBg: "#E2620F",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.62)",
  },
  {
    id: "title-mode",
    photo: "combat",
    tags: ["dark", "minimal", "bold"],
    label: "Title Mode",
    vibe: "Boxing — black & white championship mono",
    wordmark: "TITLE MODE",
    tagline: "Discipline. Focus. Glory.",
    headline: "MINDSET. TRAINING.\nCHAMPIONS.",
    body: "Boxing training, mental toughness, and a community of warriors.",
    cta: "ENTER THE RING",
    features: ["TRAINING PLANS", "MENTAL GAME", "NUTRITION", "COMMUNITY"],
    icons: ["calendar", "sparkle", "heart", "users"],
    count: "9K+",
    countLabel: "Fighters",
    extra: "+6",
    bg: "#050505",
    bgVia: "#151515",
    accent: "#FFFFFF",
    accentHover: "#D4D4D4",
    ctaBg: "#FFFFFF",
    ctaText: "#0a0a0a",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.6)",
  },
  {
    id: "wave-ryders",
    photo: "other",
    tags: ["nature", "vibrant", "sport"],
    label: "Wave Ryders",
    vibe: "Surf — cyan ocean spray",
    wordmark: "WAVE RYDERS",
    tagline: "Ride more. Worry less.",
    headline: "CHASE WAVES\nNOT LIKES",
    body: "Surf guides, gear picks, and a global community of wave chasers.",
    cta: "CATCH A WAVE",
    features: ["SURF GUIDES", "GEAR REVIEWS", "TRAVEL", "COMMUNITY"],
    icons: ["sparkle", "shop", "ticket", "users"],
    count: "7K+",
    countLabel: "Surfers",
    extra: "+5",
    bg: "#04121a",
    bgVia: "#0b3243",
    accent: "#67E8F9",
    accentHover: "#A5F3FC",
    ctaBg: "#4FD1E5",
    ctaText: "#04212b",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.66)",
  },
  {
    id: "speed-lab",
    photo: "track",
    tags: ["dark", "tech", "vibrant"],
    label: "Speed Lab",
    vibe: "Cycling — magenta dusk velocity",
    wordmark: "SPEED LAB",
    tagline: "Faster every day.",
    headline: "SPEED. POWER.\nFREEDOM.",
    body: "Cycling plans, performance tracking, and a community that rides hard.",
    cta: "JOIN THE RIDE",
    features: ["TRAINING PLANS", "PERFORMANCE TRACKING", "ROUTES", "COMMUNITY"],
    icons: ["calendar", "bolt", "ticket", "users"],
    count: "14K+",
    countLabel: "Cyclists",
    extra: "+9",
    bg: "#0a0512",
    bgVia: "#2a1040",
    accent: "#E040FB",
    accentHover: "#F0A6FF",
    ctaBg: "#7C3AED",
    ctaTo: "#A855F7",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.64)",
  },
  {
    id: "flow-state",
    photo: "gymnastics",
    tags: ["light", "minimal", "pastel"],
    label: "Flow State",
    vibe: "Yoga — light, airy, sage calm",
    wordmark: "FLOW STATE",
    tagline: "Move. Breathe. Be.",
    headline: "FIND YOUR FLOW",
    body: "Yoga classes, wellness tips, and a community that centers you.",
    cta: "START YOUR JOURNEY",
    features: ["CLASSES", "WELLNESS", "MEDITATION", "COMMUNITY"],
    icons: ["calendar", "heart", "sparkle", "users"],
    count: "8K+",
    countLabel: "Yogis",
    extra: "+7",
    bg: "#F2EFE9",
    bgVia: "#E5E1D8",
    accent: "#7C8B72",
    accentHover: "#9CAA92",
    ctaBg: "#7C8B72",
    ctaText: "#FFFFFF",
    text: "#141414",
    muted: "rgba(0,0,0,0.55)",
    light: true,
    radius: 8,
  },
  {
    id: "track-life",
    photo: "track",
    tags: ["bold", "sport", "urban"],
    label: "Track Life",
    vibe: "Track — rust clay and orange starts",
    wordmark: "TRACK LIFE",
    tagline: "Leave it all on the track.",
    headline: "SPEED IS\nA HABIT",
    body: "Workouts, race strategies, and a community obsessed with getting better.",
    cta: "JOIN THE SQUAD",
    features: ["WORKOUTS", "RACE STRATEGY", "STRENGTH", "COMMUNITY"],
    icons: ["bolt", "trophy", "flame", "users"],
    count: "11K+",
    countLabel: "Track Athletes",
    extra: "+7",
    bg: "#2b0f08",
    bgVia: "#5a1c10",
    accent: "#FF8A3D",
    accentHover: "#FFB067",
    ctaBg: "#F26522",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.68)",
  },
  {
    id: "iron-club",
    photo: "volleyball",
    tags: ["dark", "tech", "bold"],
    label: "Iron Club",
    vibe: "Strength — indigo steel gym",
    wordmark: "IRON CLUB",
    tagline: "Stronger than yesterday.",
    headline: "LIFT. FOCUS.\nREPEAT.",
    body: "Strength programs, nutrition guides, and a community that lifts together.",
    cta: "JOIN IRON CLUB",
    features: ["PROGRAMS", "NUTRITION", "PROGRESS", "COMMUNITY"],
    icons: ["calendar", "heart", "bolt", "users"],
    count: "20K+",
    countLabel: "Lifters",
    extra: "+10",
    bg: "#04060f",
    bgVia: "#101a3a",
    accent: "#6D8BFF",
    accentHover: "#A5B8FF",
    ctaBg: "#4F46E5",
    ctaTo: "#6366F1",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.62)",
  },
  {
    id: "ace-club",
    photo: "tennis",
    tags: ["light", "minimal", "sport"],
    label: "Ace Club",
    vibe: "Tennis — bright court light, lime accent",
    wordmark: "ACE CLUB",
    tagline: "Play smart. Win more.",
    headline: "GAME. SET.\nGROW.",
    body: "Tennis drills, match analysis, and a community that competes.",
    cta: "JOIN THE CLUB",
    features: ["DRILLS", "MATCH ANALYSIS", "FITNESS", "COMMUNITY"],
    icons: ["bolt", "video", "heart", "users"],
    count: "9K+",
    countLabel: "Tennis Players",
    extra: "+6",
    bg: "#F6F5F0",
    bgVia: "#E9E8E1",
    accent: "#84CC16",
    accentHover: "#A3E635",
    ctaBg: "#84CC16",
    ctaText: "#10200a",
    text: "#111111",
    muted: "rgba(0,0,0,0.55)",
    light: true,
    radius: 8,
  },
  {
    id: "cold-air",
    photo: "hockey",
    tags: ["light", "nature", "minimal"],
    label: "Cold Air",
    vibe: "Snowboard — alpine blue-grey",
    wordmark: "COLD AIR",
    tagline: "Live for the ride.",
    headline: "ADVENTURE\nAWAITS",
    body: "Snowboard tips, mountain guides, and a crew that sends it.",
    cta: "JOIN THE CREW",
    features: ["TRIPS", "GEAR", "TUTORIALS", "COMMUNITY"],
    icons: ["ticket", "shop", "video", "users"],
    count: "6K+",
    countLabel: "Riders",
    extra: "+4",
    bg: "#0b1420",
    bgVia: "#1b2c40",
    accent: "#CBD5E1",
    accentHover: "#E2E8F0",
    ctaBg: "#16273a",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.66)",
    radius: 8,
  },
  {
    id: "level-up",
    photo: "esports",
    tags: ["dark", "tech", "neon"],
    label: "Level Up",
    vibe: "Esports — violet RGB glow",
    wordmark: "LEVEL UP",
    tagline: "Play. Improve. Compete.",
    headline: "PLAY HARD\nRANK HIGHER",
    body: "Game strategies, tournaments, and a community of gamers.",
    cta: "JOIN THE ARENA",
    features: ["STRATEGIES", "TOURNAMENTS", "STATS", "COMMUNITY"],
    icons: ["sparkle", "trophy", "bolt", "users"],
    count: "15K+",
    countLabel: "Gamers",
    extra: "+11",
    bg: "#0a0616",
    bgVia: "#241046",
    accent: "#A855F7",
    accentHover: "#D8B4FE",
    ctaBg: "#7C3AED",
    ctaTo: "#A855F7",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.64)",
  },
  /* ---- Athlete reference templates (built from the provided sheets) ---- */
  {
    id: "inner-circle",
    athlete: "Travis Kelce",
    photo: "football",
    tags: ["dark", "luxury", "gold"],
    label: "Inner Circle",
    vibe: "Lifestyle & legacy — black leather and brushed gold",
    wordmark: "TRAVIS KELCE",
    tagline: "Lifestyle, Legacy. Impact. Always.",
    signature: "Travis Kelce",
    badge: "Inner Circle",
    cards: [
      ["Podcast", "New episode weekly"],
      ["Latest Drop", "Shop the collection"],
      ["Fan Club", "Members only"],
      ["Experiences", "VIP access"],
    ],
    headline: "MORE THAN THE GAME.",
    body: "Exclusive access. Real connection. Maximum impact.",
    cta: "JOIN THE INNER CIRCLE",
    features: ["PODCAST", "LATEST DROP", "FAN CLUB", "EXPERIENCES"],
    icons: ["music", "shop", "crown", "ticket"],
    count: "1.2M+",
    countLabel: "Followers",
    extra: "+87",
    bg: "#080604",
    bgVia: "#1a1206",
    accent: "#D8B36A",
    accentHover: "#F0D79B",
    ctaBg: "#C89B4A",
    ctaTo: "#EBCB89",
    ctaText: "#150e03",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.66)",
  },
  {
    id: "move-mind",
    athlete: "Monique Billings",
    photo: "other",
    tags: ["warm", "wellness", "luxury"],
    label: "Move Mind Manifest",
    vibe: "Wellness — warm sand, bronze light, calm luxury",
    wordmark: "MONIQUE BILLINGS",
    tagline: "Move. Mind. Manifest.",
    signature: "Monique",
    badge: "Inner Circle",
    cards: [
      ["Move", "Training library"],
      ["Mind", "Mindset sessions"],
      ["Manifest", "Journals & goals"],
      ["Community", "Join the circle"],
    ],
    headline: "BUILT DIFFERENT.",
    body: "Wellness is the way. Purpose is the mission.",
    cta: "JOIN THE CIRCLE",
    features: ["MOVE", "MIND", "MANIFEST", "COMMUNITY"],
    icons: ["bolt", "sparkle", "star", "users"],
    count: "500+",
    countLabel: "Workouts",
    extra: "+30",
    bg: "#0d0906",
    bgVia: "#2a1d12",
    accent: "#D9B489",
    accentHover: "#EFD5B6",
    ctaBg: "#C79C6D",
    ctaTo: "#E4C39A",
    ctaText: "#1a1009",
    text: "#F7EFE6",
    muted: "rgba(247,239,230,0.66)",
  },
  {
    id: "own-your-power",
    athlete: "Aerial Powers",
    photo: "basketball",
    tags: ["dark", "neon", "bold"],
    label: "Own Your Power",
    vibe: "Hoops & gaming — magenta arena neon",
    wordmark: "AERIAL POWERS",
    tagline: "Elite athlete. Creator. Gamer.",
    signature: "Aerial Powers",
    badge: "Inner Circle",
    cards: [
      ["Exclusive Videos", "Behind the scenes"],
      ["News & Events", "Latest updates"],
      ["Gaming", "Live streams"],
      ["Experiences", "Meet & greets"],
    ],
    headline: "OWN YOUR POWER.",
    body: "Behind the scenes, full games, live streams and VIP experiences.",
    cta: "ENTER MY WORLD",
    features: ["EXCLUSIVE VIDEOS", "NEWS & EVENTS", "GAMING & STREAMING", "EXPERIENCES"],
    icons: ["video", "news", "bolt", "ticket"],
    count: "25K+",
    countLabel: "Members",
    extra: "+18",
    bg: "#0a0410",
    bgVia: "#2b0736",
    accent: "#E838C5",
    accentHover: "#FB8AE0",
    ctaBg: "#C0209E",
    ctaTo: "#F03FD0",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.66)",
  },
  {
    id: "built-different",
    athlete: "Stephen Curry",
    photo: "basketball",
    tags: ["dark", "luxury", "gold"],
    label: "Built Different",
    vibe: "Purpose-driven hoops — warm gold spotlight",
    wordmark: "PLAYER05",
    tagline: "Beyond the game. Always the impact.",
    signature: "Curry",
    badge: "Inner Circle",
    cards: [
      ["Exclusive Videos", "Behind the scenes"],
      ["News & Events", "Latest updates"],
      ["Training", "Drills & plans"],
      ["Experiences", "VIP access"],
    ],
    headline: "BUILT DIFFERENT.",
    body: "Exclusive videos, news, training and experiences that elevate your access.",
    cta: "JOIN THE CIRCLE",
    features: ["EXCLUSIVE VIDEOS", "NEWS & EVENTS", "TRAINING", "EXPERIENCES"],
    icons: ["video", "news", "bolt", "ticket"],
    count: "25K+",
    countLabel: "Members",
    extra: "+24",
    bg: "#070502",
    bgVia: "#1d1305",
    accent: "#E0B45F",
    accentHover: "#F5D89A",
    ctaBg: "#CFA149",
    ctaTo: "#EFCE86",
    ctaText: "#130c02",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.64)",
  },
  {
    id: "built-to-lead",
    athlete: "Chris Paul",
    photo: "basketball",
    tags: ["dark", "bold", "crimson"],
    label: "Built To Lead",
    vibe: "Point-guard IQ — crimson and gold leadership",
    wordmark: "CP3",
    tagline: "Elite experiences. Exclusive content.",
    signature: "Chris Paul",
    badge: "Inner Circle",
    cards: [
      ["Film Room", "Breakdowns"],
      ["Experiences", "VIP access"],
      ["Academy", "Youth programs"],
      ["Community", "Join the circle"],
    ],
    headline: "BUILT TO LEAD.",
    body: "A community built on leadership, legacy and purpose.",
    cta: "JOIN THE CIRCLE",
    features: ["FILM ROOM", "EXPERIENCES", "ACADEMY", "COMMUNITY"],
    icons: ["video", "ticket", "trophy", "users"],
    count: "250K+",
    countLabel: "Youth impacted",
    extra: "+35",
    bg: "#0a0405",
    bgVia: "#2a0a0d",
    accent: "#D9A44A",
    accentHover: "#F1CC85",
    ctaBg: "#9E1622",
    ctaTo: "#D42836",
    ctaText: "#FFFFFF",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.64)",
  },
  {
    id: "trust-the-vision",
    athlete: "Kyrie Irving",
    photo: "basketball",
    tags: ["dark", "cosmic", "mint"],
    label: "Trust The Vision",
    vibe: "Cosmic hoops — mint aura and deep space",
    wordmark: "PLAYERSOS",
    tagline: "Culture. Vision. Legacy.",
    signature: "Kyrie",
    badge: "Inner Circle",
    cards: [
      ["Training", "Skill work"],
      ["Film Room", "Breakdowns"],
      ["Events", "Live & IRL"],
      ["Community", "Join the circle"],
    ],
    headline: "TRUST THE VISION.",
    body: "Elite experiences, exclusive content and the world inside the circle.",
    cta: "JOIN THE TRIBE",
    features: ["TRAINING", "FILM ROOM", "EVENTS", "COMMUNITY"],
    icons: ["bolt", "video", "calendar", "users"],
    count: "32K+",
    countLabel: "Members",
    extra: "+18",
    bg: "#04070a",
    bgVia: "#0b2620",
    accent: "#4FE3B0",
    accentHover: "#9BF3D4",
    ctaBg: "#2FCB99",
    ctaTo: "#6FE9BE",
    ctaText: "#04231a",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.65)",
  },
  {
    id: "serve-return-repeat",
    athlete: "Sloane Stephens",
    photo: "tennis",
    tags: ["dark", "luxury", "rose"],
    label: "Serve. Return. Repeat.",
    vibe: "Night-session tennis — deep teal court with rose gold light",
    wordmark: "SLOANE STEPHENS",
    tagline: "Grand Slam champion. Doc & Glo founder.",
    signature: "Sloane",
    badge: "Inner Circle",
    cards: [
      ["Match Film", "Point breakdowns"],
      ["Doc & Glo", "Shop the line"],
      ["Foundation", "Kids on court"],
      ["Community", "Join the circle"],
    ],
    headline: "SERVE. RETURN.\nREPEAT.",
    body: "Match film, training weeks, Doc & Glo drops and the foundation work — all in one place.",
    cta: "JOIN THE CIRCLE",
    features: ["MATCH FILM", "TRAINING", "DOC & GLO", "FOUNDATION"],
    icons: ["video", "bolt", "shop", "users"],
    count: "40K+",
    countLabel: "Members",
    extra: "+22",
    bg: "#050a0b",
    bgVia: "#0d2a2b",
    accent: "#E8A6A0",
    accentHover: "#F7D2CD",
    ctaBg: "#D2837C",
    ctaTo: "#F2B6AF",
    ctaText: "#1a0d0c",
    text: "#FFFFFF",
    muted: "rgba(255,255,255,0.66)",
  },
];

EXPERIENCE_TEMPLATES.push(...SPORT_TEMPLATE_SPECS.map(fullTemplate));


/** Apply a template's look on top of an existing experience config. */
export function applyExperienceTemplate(
  config: ExperienceConfig,
  template: ExperienceTemplate,
): ExperienceConfig {
  const ctaBg = template.theme.buttonBg;
  const ctaText = template.theme.buttonText;
  /** Every template loads its artwork into the preview — delete it there if unwanted. */
  const art = template.landing?.heroImage ?? template.photo;
  /** Full designed page set (home, social, videos, news, shop, profile…). */
  const templatePages = buildTemplatePages(template);
  const pages = Object.fromEntries(
    Object.entries(config.pages).map(([key, page]) => {
      /**
       * Templates replace, they never stack: builtin pages start from a clean
       * default so layers/art from a previously picked template are dropped
       * instead of sitting underneath the new look.
       */
      const base =
        (DEFAULT_EXPERIENCE_PAGES as Record<string, typeof page>)[key] ?? page;
      const clean = {
        ...base,
        stage: (base.stage ?? []).map((s) => ({ ...s })),
        features: (base.features ?? []).map((f) => ({ ...f })),
        memberProof: { ...base.memberProof },
      };
      let next = ctaBg && ctaText ? { ...clean, ctaBg, ctaText } : clean;
      const built = templatePages[key as keyof typeof templatePages];
      if (built) {
        next = {
          ...next,
          ...built,
          features: (built.features ?? next.features).map((f) => ({ ...f })),
          memberProof: { ...next.memberProof, ...(built.memberProof ?? {}) },
          stage: (built.stage ?? next.stage).map((s) => ({ ...s })),
        };
      }
      if (key === "landing") {
        if (template.landing) {
          next = {
            ...next,
            ...template.landing,
            features: (template.landing.features ?? next.features).map((f) => ({ ...f })),
            memberProof: { ...next.memberProof, ...(template.landing.memberProof ?? {}) },
            stage: (template.landing.stage ?? next.stage).map((s) => ({ ...s })),
          };
        }
        if (art) {
          next = {
            ...next,
            heroImage: art,
            heroFit: next.heroFit || "cover",
            // make sure the hero slot is visible so the art always lands in the preview
            stage: (next.stage ?? []).map((s) =>
              (s.id === "hero" || s.role === "hero") ? { ...s, hidden: false } : s,
            ),
          };
        }
      }
      return [key, next];
    }),
  ) as ExperienceConfig["pages"];

  const navTabs = TEMPLATE_NAV_TABS[template.id];

  return {
    ...config,
    brand: { ...config.brand, ...template.brand },
    theme: { ...config.theme, ...template.theme },
    effects: { ...config.effects, ...template.effects },
    nav: navTabs
      ? {
          ...config.nav,
          tabs: navTabs.map((t) => ({ ...t })),
          activeColor: template.theme.accent ?? config.nav.activeColor,
          bg: template.theme.bg ?? config.nav.bg,
        }
      : config.nav,
    pages,
  };
}



/** Best-guess of which template the current theme came from (accent match). */
export function detectExperienceTemplate(config: ExperienceConfig): string | null {
  const accent = config.theme.accent?.toUpperCase();
  return (
    EXPERIENCE_TEMPLATES.find((t) => t.theme.accent?.toUpperCase() === accent)?.id ?? null
  );
}
